# -*- coding: utf-8 -*-
"""Bank_transaction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wPONfzZAhIe5kyTDgELNe6ncRbQ9XwPB
"""

from datetime import datetime

PASSWORD = "bank123"

def deposit(balance, transactions):
    amount = float(input("Enter deposit amount: "))
    if amount > 0:
        balance += amount
        time_now = datetime.now().strftime("%d-%m-%Y %H:%M:%S")
        transactions.append(f"Deposited ₹{amount:.2f} on {time_now}")
        print("Amount deposited successfully.")
    else:
        print("Invalid amount.")
    return balance


def withdraw(balance, transactions):
    amount = float(input("Enter withdrawal amount: "))
    if amount > 0 and amount <= balance:
        balance -= amount
        time_now = datetime.now().strftime("%d-%m-%Y %H:%M:%S")
        transactions.append(f"Withdrew ₹{amount:.2f} on {time_now}")
        print("Amount withdrawn successfully.")
    else:
        print("Insufficient balance or invalid amount.")
    return balance


def check_balance(balance):
    print(f"Current balance: ₹{balance:.2f}")


def view_transactions(transactions):
    if transactions:
        print("Transaction History:")
        for t in transactions:
            print(t)
    else:
        print("No transactions yet.")


# Main Program
entered_password = input("Enter password to access your account: ")

if entered_password == PASSWORD:
    balance = 0
    transactions = []

    while True:
        print("\n1.Deposit  2.Withdraw  3.Check Balance  4.View Transactions  5.Exit")
        choice = input("Enter choice: ")

        if choice == '1':
            balance = deposit(balance, transactions)

        elif choice == '2':
            balance = withdraw(balance, transactions)

        elif choice == '3':
            check_balance(balance)

        elif choice == '4':
            view_transactions(transactions)

        elif choice == '5':
            print("Exiting the system.")
            break

        else:
            print("Invalid choice.")
else:
    print("Incorrect password. Access denied.")